### ISSUE TITLE
Suggestions by Jason

### ISSUE THREAD

**Issue by SaptakS** [SaptakS/saptaks.github.io#17]
- [ ] Make the about section same height as the head section
- [ ] `My core areas of dabbling are python and javascript and related frameworks.` -> Make this active.
- [ ] `help out people` -> `help people`
- [ ] reduce the width of the bars above and below Github

Thanks @jasonbraganza

**Comment by jasonbraganza** [comment]
- [ ] that I have been contributing to.  -> that I contribute to.

@SaptakS any time :)

**Comment by SaptakS** [comment]
Closing this given the website and content has changed after that. @jasonbraganza feel free to review again and give some tips. :)
